name: muler_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - setuptools
  - numpy=1.26.4 #There are numerous incompatibilities introduced by numpy>2.0.0 so we are going to stick to this version for now
  - scipy
  - matplotlib
  - astropy
  - astroquery
  - tqdm
  - gwcs
  - ndcube
  - pandas
  - bokeh
  - jupyter
  - ipython
  - seaborn
  - importlib_resources
  - h5py
  - pytest
  - sphinx # for documentation and testing
  - nbsphinx # for documentation and testing
  - numpydoc # for documentation and testing
  - sphinx-automodapi # for documentation and testing
  - black
  - isort
  - tox
  - coverage
  - coveralls
  - twine
  - dust_extinction
  - pip
  - pip:
      - sphinx-material
      - celerite2
      - specutils>=2.1
      - tynt
      - gollum=git+https://github.com/BrownDwarf/gollum.git#egg=gollum

